project:
  type: website
  output-dir: docs

website:
  title: "Arthur Oulès"
  description: "Arthur Oulès' personnal website containing hobbies and teaching ressources."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: wildlife_photography.qmd
        text: Wildlife Photography
      - href: origami.qmd
        text: Origami
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/Arthur-Oules/Arthur-Oules.github.io
  page-footer:
    border: true
    left: |
      [Powered by [[{{< iconify simple-icons:quarto title='Quarto Logo' label='Quarto Logo' >}}]{style="color:#74aadb;"} Quarto](https://quarto.org).]{.smallertext}
    center: >
       {{< iconify cib creative-commons >}} {{< iconify cib creative-commons-by >}} {{< iconify cib creative-commons-nc >}} [This work is licensed under <http://creativecommons.org/licenses/by-nc/4.0/>.]{.smallertext}
    right: |
     [2025 Arthur Oulès]{.smallertext}

format:
  html:
    theme: 
      light: [lux, custom.scss]
      dark: [lux, custom-dark.scss]
    lightbox: true
    css: styles.css
    link-external-newwindow: true
    link-external-icon: true
    toc: true
    linestretch: 1.2

execute:
    freeze: auto

editor: source